server:
  port: 8081
spring:
  application:
    name: rentacar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true